version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      rabbitmq_go_net:
        aliases:
          - rabbit.client.local
  files_api:
    build:
      context: ./filesAPI
      target: builder
    env_file: ./.env.dev
    expose:
      - "8080"
    volumes:
      - ./filesAPI:/go/src/app
    command: go run ./
    depends_on:
      - rabbitmq
    networks:
      rabbitmq_go_net:
        aliases:
          - file.upload.local
  processing_api:
    build:
      context: .
      target: builder
    env_file: ./.env.dev
    volumes:
      - ./filesAPI/images:/go/src/app/images
    command: go run ./
    depends_on:
      - rabbitmq
    networks:
      rabbitmq_go_net:

networks:
  rabbitmq_go_net: